export type ThemeType = {
  colors: {
    titleLight: string;
    titleNormal: string;
    titleBold: string;
    titleBlack: string;
    titleQuiz: string;
    accented: string;
    primary: string;
    secondary: string;
    terciary: string;
    buttonBack: string;
    buttonBackTitle: string;
    optionNormalTitle: string;
    optionSelectedTitle: string;
    optionNormalBorder: string;
    optionNormalBackground: string;
    optionSuccessBorder: string;
    optionSuccessBackground: string;
    optionErrorBorder: string;
    optionErrorBackground: string;
    backGradientStart: string;
    backGradientEnd: string;
    buttonActionTitle: string;
    buttonActionOutileneTitle: string;
    buttonActionOutileneBorder: string;
    bottonNavigationBack: string;
    bottomNavigationBorder: string;
    bottonNavigationTitle: string;
    bottonNavigationTitleFocus: string;
    cardTitle: string;
    cardSubtitle: string;
    cardProgressPrimary: string;
    cardProgressSecondary: string;
    cardProgressBackground: string;
    cardProgressBorder: string;
    cardQuizTitle: string;
    cardQuizSubtitle: string;
    cardQuizBackground: string;
    cardQuizBorder: string;
    cardSubcategoryTitle: string;
    cardSubcategorySubtitle: string;
    cardSubcategoryQuizCount: string;
    toggleBorderActive: string;
    toggleActiveBackground: string;
    toggleInActiveBackground: string;
    toggleBorderInActive: string;
    inputPlaceholder: string;
  };
  spacing: { sm: number; md: number; lg: number };
  fontSizes: {
    xxs: number;
    xs: number;
    sm: number;
    md: number;
    lg: number;
    xl: number;
    xl2: number;
    xl3: number;
    xl4: number;
    xl5: number;
    xl6: number;
    xl7: number;
  };
  fontLogo: { regular: string };
  fontFamily: { regular: string; medium: string; semibold: string; bold: string };
};
