import { ThemeType } from './colorsTheme';
import { scale, verticalScale } from 'react-native-size-matters';
import { RFValue } from 'react-native-responsive-fontsize';

export const darkTheme: ThemeType = {
  colors: {
    titleLight: '#D8DDE5',
    titleNormal: '#D8DDE5',
    titleBold: '#F0F5FB',
    titleBlack: '#151A1E',
    titleQuiz: '#F0F5FB',
    accented: '#F4A000',
    primary: '#F6BB0B',
    secondary: '#FDEDA9',
    terciary: '#3E4C59',
    buttonBack: '#323F4B',
    buttonBackTitle: '#F0F5FB',
    optionNormalTitle: '#F0F5FB',
    optionSelectedTitle: '#2B3440',
    optionNormalBorder: '#52606D',
    optionNormalBackground: '#3E4C59',
    optionSuccessBorder: '#96C637',
    optionSuccessBackground: '#E3FDAC',
    optionErrorBorder: '#EE3B2B',
    optionErrorBackground: '#F8D0CC',
    backGradientStart: '#1F2933',
    backGradientEnd: '#323F4B',
    buttonActionTitle: '#151A1E',
    buttonActionOutileneTitle: '#F0F5FB',
    buttonActionOutileneBorder: '#7B8794',
    bottonNavigationBack: '#3E4C59',
    bottomNavigationBorder: '#51606D',
    bottonNavigationTitle: '#9AA5B1',
    bottonNavigationTitleFocus: '#F0F5FB',
    cardTitle: '#151A1E',
    cardSubtitle: '#434E5D',
    cardProgressPrimary: '#F48200',
    cardProgressSecondary: '#F4A000',
    cardProgressBackground: '#F8E287',
    cardProgressBorder: '#F9D341',
    cardQuizTitle: '#D8DDE5',
    cardQuizSubtitle: '#D8DDE5',
    cardQuizBackground: '#3E4C59',
    cardQuizBorder: '#52606D',
    cardSubcategoryTitle: '#D8DDE5',
    cardSubcategorySubtitle: '#ADB1B7',
    cardSubcategoryQuizCount: '#F0F5FB',
    toggleBorderActive: '#52606D',
    toggleActiveBackground: '#323F4B',
    toggleInActiveBackground: '#FDEEA9',
    toggleBorderInActive: '#FDE168',
    inputPlaceholder: '#798391',
    background: '#0C1624',
  },
  vSpacings: {
    xs: verticalScale(8),
    sm: verticalScale(16),
    md: verticalScale(24),
    lg: verticalScale(32),
    xl: verticalScale(40),
    xl2: verticalScale(48),
    xl3: verticalScale(56),
    xl4: verticalScale(64),
  },
  hSpacings: {
    xs: scale(8),
    sm: scale(16),
    md: scale(24),
    lg: scale(32),
    xl: scale(40),
    xl2: scale(48),
    xl3: scale(56),
    xl4: scale(64),
  },
  fontSizes: {
    xxs: RFValue(10),
    xs: RFValue(12),
    sm: RFValue(14),
    md: RFValue(16),
    lg: RFValue(18),
    xl: RFValue(20),
    xl2: RFValue(22),
    xl3: RFValue(24),
    xl4: RFValue(26),
    xl5: RFValue(28),
    xl6: RFValue(30),
    xl7: RFValue(34),
  },
  fontLogo: { regular: 'Courgette_400Regular' },
  fontFamily: {
    regular: 'Nunito_400Regular',
    medium: 'Nunito_500Medium',
    semibold: 'Nunito_600SemiBold',
    bold: 'Nunito_700Bold',
  },
};
