import { RFValue } from 'react-native-responsive-fontsize';
import { scale, verticalScale } from 'react-native-size-matters';
import { ThemeType } from './colorsTheme';

export const lightTheme: ThemeType = {
  colors: {
    titleLight: '#434E5D',
    titleNormal: '#2B3440',
    titleBold: '#151A1E',
    titleBlack: '#151A1E',
    titleQuiz: '#082C41',
    accented: '#F4A000',
    primary: '#F6BB0B',
    secondary: '#FDEDA9',
    terciary: '#FCFCFC',
    buttonBack: '#FDEDA9',
    buttonBackTitle: '#151A1E',
    optionNormalTitle: '#2B3440',
    optionSelectedTitle: '#2B3440',
    optionNormalBorder: '#CACCD0',
    optionNormalBackground: '#FCFCFC',
    optionSuccessBorder: '#C2E36A',
    optionSuccessBackground: '#F1FED6',
    optionErrorBorder: '#F78D83',
    optionErrorBackground: '#FCE7E5',
    backGradientStart: '#FEF7DC',
    backGradientEnd: '#FFFDF4',
    buttonActionTitle: '#151A1E',
    buttonActionOutileneTitle: '#151A1E',
    buttonActionOutileneBorder: '#434E5D',
    bottonNavigationBack: '#FDE168',
    bottomNavigationBorder: '#F9D341',
    bottonNavigationTitle: '#434E5D',
    bottonNavigationTitleFocus: '#434E5D',
    cardTitle: '#151A1E',
    cardSubtitle: '#434E5D',
    cardProgressPrimary: '#F48200',
    cardProgressSecondary: '#F4A000',
    cardProgressBackground: '#F8E287',
    cardProgressBorder: '#F9D341',
    cardQuizTitle: '#2B3440',
    cardQuizSubtitle: '#2B3440',
    cardQuizBackground: '#FCFCFC',
    cardQuizBorder: '#D8DDE5',
    cardSubcategoryTitle: '#151A1E',
    cardSubcategorySubtitle: '#434E5D',
    cardSubcategoryQuizCount: '#798391',
    toggleBorderActive: '#52606D',
    toggleActiveBackground: '#323F4B',
    toggleInActiveBackground: '#FDEEA9',
    toggleBorderInActive: '#FDE168',
    inputPlaceholder: '#798391',
  },
  vSpacings: {
    xs: verticalScale(8),
    sm: verticalScale(16),
    md: verticalScale(24),
    lg: verticalScale(32),
    xl: verticalScale(40),
    xl2: verticalScale(48),
    xl3: verticalScale(56),
    xl4: verticalScale(64),
  },
  hSpacings: {
    xs: scale(8),
    sm: scale(16),
    md: scale(24),
    lg: scale(32),
    xl: scale(40),
    xl2: scale(48),
    xl3: scale(56),
    xl4: scale(64),
  },
  fontSizes: {
    xxs: RFValue(10),
    xs: RFValue(12),
    sm: RFValue(14),
    md: RFValue(16),
    lg: RFValue(18),
    xl: RFValue(20),
    xl2: RFValue(22),
    xl3: RFValue(24),
    xl4: RFValue(26),
    xl5: RFValue(28),
    xl6: RFValue(30),
    xl7: RFValue(34),
  },
  fontLogo: { regular: 'Courgette_400Regular' },
  fontFamily: {
    regular: 'Nunito_400Regular',
    medium: 'Nunito_500Medium',
    semibold: 'Nunito_600SemiBold',
    bold: 'Nunito_700Bold',
  },
};
